import = [
    "~/.config/alacritty/themes/themes/alacritty_0_12.toml"
]

[font]
offset.y = 1
size = 11.0

[window]
padding.x = 10
padding.y = 10
dynamic_padding = true
#decorations = "Transparent"
opacity = 1
